import pytest
from fastapi.testclient import TestClient
from myapp.app import app
from datetime import date

client = TestClient(app)

def test_root():
    """
    Test the root endpoint by sending a GET request to "/" and checking the response status code and JSON body.
    """
    response = client.get("/")
    assert response.status_code == 200
    assert response.json() == {"message": "Welcome to the FastAPI application!"}


# This test was generated by Qodo Cover
def test_fizzbuzz_invalid_number():
    response = client.get("/fizzbuzz/0")
    assert response.status_code == 400
    assert response.json() == {"detail": "Number must be at least 1"}


# This test was generated by Qodo Cover
def test_fizzbuzz_valid_number():
    response = client.get("/fizzbuzz/15")
    assert response.status_code == 200
    assert response.json() == {
        "sequence": [
            "1", "2", "Fizz", "4", "Buzz", "Fizz", "7", "8", "Fizz", "Buzz",
            "11", "Fizz", "13", "14", "FizzBuzz"
        ]
    }

