import { expect } from 'chai';
import 'mocha';
import AdvancedCalculator from '../src/modules/AdvancedCalculator';

describe('AdvancedCalculator', () => {
    let calc: AdvancedCalculator;

    beforeEach(() => {
        calc = new AdvancedCalculator();
    });

    it('should compute factorial correctly', () => {
        // Press digits "5"
        calc.buttonPressed({ type: 'number', value: '5' });
        expect(calc.onDisplay).to.equal('5');

        // factorial of 5
        const result = calc.factorial();
        expect(result).to.equal(120);
        expect(calc.onDisplay).to.equal('120');
    });

    // This test was generated by Qodo Cover
    it('should clear history', () => {
        // Perform some operations
        calc.buttonPressed({ type: 'number', value: '5' });
        calc.factorial(); // 5! = 120
        calc.buttonPressed({ type: 'number', value: '16' });
        calc.sqrt(); // sqrt(16) = 4
    
        // Clear history
        calc.clearHistory();
        const history = calc.getHistory();
        expect(history).to.be.an('array').that.is.empty;
    });


    // This test was generated by Qodo Cover
    it('should return an empty history initially', () => {
        const history = calc.getHistory();
        expect(history).to.be.an('array').that.is.empty;
    });


    // This test was generated by Qodo Cover
    it('should throw an error when sqrt is called without a number on display', () => {
        expect(() => calc.sqrt()).to.throw('No number on display to compute sqrt');
    });


    // This test was generated by Qodo Cover
    it('should compute square root correctly', () => {
        // Press digits "16"
        calc.buttonPressed({ type: 'number', value: '16' });
        expect(calc.onDisplay).to.equal('16');
    
        // square root of 16
        const result = calc.sqrt();
        expect(result).to.equal(4);
        expect(calc.onDisplay).to.equal('4');
    });


    // This test was generated by Qodo Cover
    it('should throw an error when factorial is called without a number on display', () => {
        expect(() => calc.factorial()).to.throw('No number on display to compute factorial');
    });



});