import { expect } from 'chai';
import 'mocha';
import HistoryManager, { HistoryRecord } from '../src/modules/HistoryManager';

describe('HistoryManager', () => {
    let historyManager: HistoryManager;

    beforeEach(() => {
        historyManager = new HistoryManager();
    });

    it('should add a record and retrieve it', () => {
        const record: HistoryRecord = {
            operationName: 'add',
            leftOperand: 2,
            rightOperand: 3,
            result: 5,
        };
        historyManager.addRecord(record);

        const allHistory = historyManager.getAllHistory();
        expect(allHistory).to.have.lengthOf(1);
        expect(allHistory[0]).to.deep.equal(record);
    });

    // This test was generated by Qodo Cover
    it('should return all records matching the given operation name', () => {
        const record1: HistoryRecord = {
            operationName: 'add',
            leftOperand: 2,
            rightOperand: 3,
            result: 5,
        };
        const record2: HistoryRecord = {
            operationName: 'subtract',
            leftOperand: 10,
            rightOperand: 4,
            result: 6,
        };
        const record3: HistoryRecord = {
            operationName: 'add',
            leftOperand: 1,
            rightOperand: 1,
            result: 2,
        };
        historyManager.addRecord(record1);
        historyManager.addRecord(record2);
        historyManager.addRecord(record3);
    
        const searchResults = historyManager.searchHistoryByOperationName('add');
        expect(searchResults).to.have.lengthOf(2);
        expect(searchResults).to.deep.include(record1);
        expect(searchResults).to.deep.include(record3);
    });


    // This test was generated by Qodo Cover
    it('should return null when undoing the last operation on an empty history', () => {
        const undoneRecord = historyManager.undoLastOperation();
        expect(undoneRecord).to.be.null;
    });


    // This test was generated by Qodo Cover
    it('should return null when getting the last record from an empty history', () => {
        const lastRecord = historyManager.getLastRecord();
        expect(lastRecord).to.be.null;
    });


    // This test was generated by Qodo Cover
    it('should export history as a JSON string', () => {
        const record1: HistoryRecord = {
            operationName: 'add',
            leftOperand: 1,
            rightOperand: 1,
            result: 2,
        };
        const record2: HistoryRecord = {
            operationName: 'subtract',
            leftOperand: 5,
            rightOperand: 3,
            result: 2,
        };
        historyManager.addRecord(record1);
        historyManager.addRecord(record2);
    
        const exportedHistory = historyManager.exportHistory();
        const expectedJson = JSON.stringify([record1, record2]);
        expect(exportedHistory).to.equal(expectedJson);
    });


    // This test was generated by Qodo Cover
    it('should clear the history', () => {
        const record: HistoryRecord = {
            operationName: 'divide',
            leftOperand: 10,
            rightOperand: 2,
            result: 5,
        };
        historyManager.addRecord(record);
    
        historyManager.clearHistory();
        const allHistory = historyManager.getAllHistory();
        expect(allHistory).to.be.empty;
    });


    // This test was generated by Qodo Cover
    it('should undo the last operation', () => {
        const record1: HistoryRecord = {
            operationName: 'add',
            leftOperand: 2,
            rightOperand: 3,
            result: 5,
        };
        const record2: HistoryRecord = {
            operationName: 'multiply',
            leftOperand: 4,
            rightOperand: 5,
            result: 20,
        };
        historyManager.addRecord(record1);
        historyManager.addRecord(record2);
    
        const undoneRecord = historyManager.undoLastOperation();
        expect(undoneRecord).to.deep.equal(record2);
    
        const allHistory = historyManager.getAllHistory();
        expect(allHistory).to.have.lengthOf(1);
        expect(allHistory[0]).to.deep.equal(record1);
    });


    // This test was generated by Qodo Cover
    it('should return the last record', () => {
        const record1: HistoryRecord = {
            operationName: 'add',
            leftOperand: 2,
            rightOperand: 3,
            result: 5,
        };
        const record2: HistoryRecord = {
            operationName: 'subtract',
            leftOperand: 10,
            rightOperand: 4,
            result: 6,
        };
        historyManager.addRecord(record1);
        historyManager.addRecord(record2);
    
        const lastRecord = historyManager.getLastRecord();
        expect(lastRecord).to.deep.equal(record2);
    });



});